/* generated by tools/gen_assets.py - do not edit */
#ifndef ASSETS_H
#define ASSETS_H
#include <stdint.h>

#define WORLD_COLS 192
#define WORLD_ROWS 16
#define NUM_TARGETS 13
#define SPR_TILE_COUNT 50
#define BG_TILE_BASE 64
#define BG_TILE_COUNT 104
#define RUNWAY_HOME_X0 40
#define RUNWAY_HOME_X1 168
#define GROUND_MIN_Y 64
#define ENEMY_BASE_X 1400
#define T_FACTORY 0
#define T_FUEL 1
#define T_TANK 2
#define T_HANGAR 3
#define SPR_PLANE 0
#define SPR_BULLET 32
#define SPR_BOMB_V 34
#define SPR_BOMB_D 36
#define SPR_DEBRIS 38
#define SPR_EXPL_A 40
#define SPR_EXPL_B 42
#define SPR_BIRD_A 44
#define SPR_BIRD_B 46
#define SPR_SMOKE 48
#define BGT_SKY 64
#define BGT_DIRT 65
#define BGT_GRASS 66
#define BGT_SLOPE_UP 67
#define BGT_SLOPE_DN 68
#define BGT_RUNWAY 69
#define BGT_FACTORY 70
#define BGT_FUEL 74
#define BGT_TANK 78
#define BGT_HANGAR 82
#define BGT_RUBBLE 86
#define BGT_HOMEFLAG 90
#define BGT_TREE 94
#define BGT_FONT 96
#define BGT_BAR 144
#define BGT_HUD_BOMB 153
#define BGT_HUD_PLANE 154
#define BGT_HUD_LINE 155
#define BGT_MINIMAP 156

extern const uint8_t spr_tiles[800];
extern const uint8_t bg_tiles[1664];
extern const uint8_t world_init[3072];
extern const uint8_t ground_vtx[193];
extern const uint8_t minimap_base[192];
extern const uint8_t target_init[39];
extern const int8_t cos64[16];
extern const int8_t sin64[16];
extern const uint8_t charmap[96];

#endif
